from pathlib import Path
import hashlib,json,os,datetime
R=Path('/home/inspur/aic_video_work').resolve()
O=R/'round3_20260912'; O.mkdir(exist_ok=True)
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
protected=[p for d in ['training_round2_20260910','runs'] for p in (R/d).rglob('*') if p.is_file() and p.suffix in ['.json','.jsonl','.safetensors']]
before={str(p.relative_to(R)):sha(p) for p in protected}
report={'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'removed_caches':[],'deduplicated':[],'bytes_reclaimed':0}
# Only generated bytecode in task source directories, never environments or vendor.
for name in ['training','training_v2','inference','inference_v2','inference_recovery','evaluation','evaluation_v2','data_audit','training_round2_20260910']:
 for p in (R/name).rglob('*.pyc'):
  if p.is_symlink() or '__pycache__' not in p.parts: continue
  if not p.resolve().is_relative_to(R): raise RuntimeError('path escape')
  report['removed_caches'].append({'path':str(p),'bytes':p.stat().st_size})
  report['bytes_reclaimed']+=p.stat().st_size
  p.unlink()
# Keep both named checkpoints; identical best/last weights can share disk blocks.
for run in ['smoke_v1','formal_v1']:
 a=R/'training_round2_20260910'/run/'best/adapter_model.safetensors'
 b=R/'training_round2_20260910'/run/'last/adapter_model.safetensors'
 if a.is_file() and b.is_file() and not a.is_symlink() and not b.is_symlink() and sha(a)==sha(b) and a.stat().st_ino!=b.stat().st_ino:
  size=b.stat().st_size
  tmp=b.with_name(b.name+'.dedup-link')
  if tmp.exists(): raise RuntimeError('unexpected temp')
  os.link(a,tmp); os.replace(tmp,b)
  report['deduplicated'].append({'retained_paths':[str(a),str(b)],'sha256':sha(a),'bytes':size,'method':'hardlink_identical_immutable_checkpoints'})
  report['bytes_reclaimed']+=size
assert all((R/k).is_file() and sha(R/k)==v for k,v in before.items())
report['protected_file_count']=len(before); report['protected_hashes_unchanged']=True
(O/'cleanup_protected_hashes.json').write_text(json.dumps(before,indent=2))
(O/'cleanup_report.json').write_text(json.dumps(report,indent=2))
print(json.dumps({k:v for k,v in report.items() if k!='removed_caches'}))
